### ISSUE TITLE
Fansly: Videos & preview images not downloading

### ISSUE THREAD

**Issue by e2489** [DIGITALCRIMINALS/OnlyFans#12]
Normal content gets scraped and downloaded, videos & PPV preview images do not.

**Comment by DIGITALCRIMINALS** [comment]
What's the username?

**Comment by e2489** [comment]
This is the case for all users I've tried.

**Comment by DeepSeaOne** [comment]
> What's the username?

To provide an example, tebiird. Active subscription, paid and free posts get scraped but not messages.

**Comment by DIGITALCRIMINALS** [comment]
I'll be working on downloading messages within 24 hours

**Comment by DIGITALCRIMINALS** [comment]
> I'll be working on downloading messages within 24 hours

This was a lie, but I've finally done it (I think). I know tiered content is downloading, not sure about paid, so you could try it out.

**Comment by DeepSeaOne** [comment]
> 

Just tried it out after updating, looks like it will scrape some paid images but not paid video for some reason. All are the same account mentioned above. I'll be honest with OF reverting their ToS changes, scraping both OF and Fansly is sort of a moot point. I appreciate the work you've done for us!

**Comment by DIGITALCRIMINALS** [comment]
I don't have access to paid content on Fansly

**Comment by norogodod** [comment]
Hi! 
Following up on this thread =)
Just discovered your script today, and it's working out better for me on fansly than on onlyfans at the moment. 
(for me OF is not reacting to 1 = video promt but tries to download all, but I'll state that issue elsewhere)

However Fansly also have some issues. It seem that it's the preview picture from the feed that is getting downloaded instead of the original. (Preview usually covers the fun parts with smileys). 

There is another creator who have fixed the issue in his "https://github.com/Avnsx/fansly". However, his software is very limited in changing filenames, directories and such. Also the quality of the pictures downloaded is lower via that software.

Something you could to look into? 
(Hit me up if you need access to a feed that is part of a higher tier. For testing it out yourself.)

**Comment by DIGITALCRIMINALS** [comment]
> Hi! Following up on this thread =) Just discovered your script today, and it's working out better for me on fansly than on onlyfans at the moment. (for me OF is not reacting to "1 = images" prompt but tries to download all, but I'll state that issue elsewhere)
> 
> However Fansly also have some issues. It seem that it's the preview picture from the feed that is getting downloaded instead of the original. (Preview usually covers the fun parts with smileys).
> 
> There is another creator who have fixed the issue in his "https://github.com/Avnsx/fansly". However, his software is very limited in changing filenames, directories and such. Also the quality of the pictures downloaded is lower via that software.
> 
> Something you could to look into? (Hit me up if you need access to a feed that is part of a higher tier. For testing it out yourself.)

I'd need access to your account to fix that

**Comment by norogodod** [comment]
Hi! My subscription on Fansly has run out at the moment and I have no plan to re-subscribe yet. So we'll have to put it all on hold for now. 

Thanks for reaching back!

**Comment by DIGITALCRIMINALS** [comment]
I've fixed paid content
