### ISSUE TITLE
UW PICO?

### ISSUE THREAD

**Issue by wt3459** [DIGITALCRIMINALS/OnlyFans#421]
Tried running the newest version, but when I run the python script Terminal gives me:

`  UW PICO 5.09                  File: .settings/config.json                     

{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {

`

There's numerous options below, but typing any of these does nothing:
`^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   
^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell`

The only "solution" I found was to quit terminal and run again (and several other times). I've added all my user info correctly, but then there's auth problems, so I'm not sure if my approach of running the program multiple times is actually the problem. Anyone have an issue like this?

**Comment by leightonstarwalt** [comment]
If this is the first time you're running the script after configuring, this behavior is intentional, AFAIK.

The files for site and script settings are opened in succession with a text editor called pico to allow you to make changes directly to the files from a terminal window.

To perform those options at the bottom of the screen, for example: `^O WriteOut` can be performed by pressing CTRL+O.
CTRL+G for help, etc.
For more help with pico, try running `man pico` from a terminal window, or view [here](https://linux.die.net/man/1/pico)


As for the auth errors, what exactly are you seeing? Most likely an issue with your auth.json file.

**Comment by wt3459** [comment]
If that's the case, I think I've done everything correctly and still getting auth errors:
```
Auth (V1) Attempt 1/10
Auth 404'ed
```
and
 
```
TypeError: 'NoneType' object does not support item assignment
```

I tried using OnlyFans cookie helper, as well as manually inspecting, both isn't working. Updated it to the latest version/installed the new libraries. Any idea on what could be the problem?
