### ISSUE TITLE
The scraper not being fixed/supported?

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINALS/OnlyFans#423]
Is this scraper no longer being supported? Seems like it is. It's so buggy now, not worth even using anymore. Oh well....

**Comment by Jarsky** [comment]
> Is this scraper no longer being supported? Seems like it is. It's so buggy now, not worth even using anymore. Oh well....

If youre still struggling, or are having a new issue why not post the actual issue instead of meaningless passive agressive posts? 
People have lives, they cant constantly be working on 1 single project their entire life. Perhaps the dev has some stuff going on. 

The script is still working just fine on Linux. 

Seems to work just fine here on Windows 11 as well. 
There is an issue with Poetry installing the requirements but you can easily manually install the package its complaining about by running `pip install <modulename>`

I had a quick look and the packages are being pulled down to the cache %AppData%\Local\pypoetry\Cache\virtualenvs\ultimascraper-AavXaVAm-py3.10\Lib\site-packages  
Just doesnt seem that the project is referencing this folder and pythong is trying to run them from
%AppData%\Local\Programs\Python\Python310\Lib\site-packages

I dont really work much with Python so not sure myself how this works, but its easy enough to copy the packages from 1 folder to the other, or run the command above.

**Comment by DIGITALCRIMINALS** [comment]
> > Is this scraper no longer being supported? Seems like it is. It's so buggy now, not worth even using anymore. Oh well....
> 
> If youre still struggling, or are having a new issue why not post the actual issue instead of meaningless passive agressive posts? People have lives, they cant constantly be working on 1 single project their entire life. Perhaps the dev has some stuff going on.

Few understand this, been working on this scraper for 3 years straight everyday, I'm just taking a break.
