### ISSUE TITLE
[OnlyFans] Issue downloading paid content and bundle messages

### ISSUE THREAD

**Issue by ppsoong** [DIGITALCRIMINALS/OnlyFans#442]
I've had issues with the scraper not downloading some content for the past 2 months. I've noticed the ignored files are ones that come from:

* Paid content sent in messages
* Paid and unpaid content sent in a bundle or from messages with multiple files
* Longer videos sent in messages. For example, a 2 minute video was downloaded from one user's messages, but none of the longer ones (ex: >8 min) from them were. Both messages were not locked or paid messages.

I believe this is related to #404 and #397. I've tried turning both `messages` and `paid_content` to false like #397 suggested. I've also tried only having `paid_content` enabled, the scraper says it downloads things, but I'm still missing the paid content.

Has anyone else encountered this same issue and found a fix other than what's mentioned in #397? I saw that someone sent @DIGITALCRIMINALS their auth file a few weeks ago (#404), is there an update on this?

Windows 10 Pro N
Scraper v8.0.0 (with most recent commits from 4/25)
Python 3.10.4

**Comment by RB1875** [comment]
this issue seems to stop and start for me, ran it each day Monday thru Wednesday (this week, W/C 16th May '22) and nothing that was bought or sent in a bundle was downloaded, today as if by magic, it starts picking them up again.

I'd tried the turning `messages` and `paid_content` in the auth.json to false, running the scraper and then changing back to true, but no joy. Left it on true the past 2 days and now it works again.

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed
