### ISSUE TITLE
[OnlyFans] Date stripped from archived post names

### ISSUE THREAD

**Issue by fl4shforward** [DIGITALCRIMINALS/OnlyFans#480]
With pathnames set as following, date does not prefix archived posts.

```
"file_directory_format": "{site_name}/{model_username}/{value}",
"filename_format": "{date}_{api_type}_{filename}.{ext}",
```

![image](https://user-images.githubusercontent.com/93709591/170887122-9e1bce62-065d-43df-8596-bae2b5715b77.png)
Top is normal post, bottom is archived post.

[Edit]
Pretty sure part of the issue comes from here, but I don't think that's all.
https://github.com/DIGITALCRIMINALS/OnlyFans/blob/85aec02065f6065c5b99b6caedec20ce947ffc2d/modules/onlyfans.py#L175-L179

[Edit 2]
Did some tests and yeah, it's definitely those lines, since I'm using {api_type} in my filename instead of folder name, os.path.join() is causing the issue.

Replaced line 176 by
`"Archived" + api_type`
for debug purposes and it named my files correctly. (did the same in OFRenamer too)

![image](https://user-images.githubusercontent.com/93709591/173422333-cd3cde02-9a48-4978-aa3d-4d1e9664d23b.png)

**Comment by Beareschal** [comment]
Couple of things I could think of: 
Double-check if you have renamer Checked on still if those posts are still showing on their profile. 
A deletion of metadata at some point could cause an issue potentially.
That's all I got unless there's a real bug that I am unable to reproduce since I don't use the date as part of the filename.

**Comment by DIGITALCRIMINALS** [comment]
Thanks, I've fixed it and it now looks like
`20220120_ArchivedPosts_2316x3088`
Just have to update the script
