### ISSUE TITLE
Onlyfans Isn't scraping Paid Content Anymore

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#493]
anyone else getting this issue?

**Comment by ashby-lat** [comment]
I am. 

Neither paid posts nor paid messages.

Tried messing with the `config.json` file, setting `"messages": false"` (despite paid messages being exactly the thing I want to scrape—I'd found the recommendation in a different issue, where the poster said that the scraper would still scrape messages). 

I am successfully downloading free content (though not sure if it's *all* free content since additional free content was downloaded during one of my tests).

Any ideas? Here's the config file:

```
{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": 0,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "a618f966ebf711ecac988a094eea7fb2"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "Videos",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": false,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}
```

**Comment by cwazy2020** [comment]
There is definitely a problem.  I am also only downloading free content.

**Comment by Graphicscore** [comment]
Have the same issue.

**Comment by xk44** [comment]
Same issue.
`Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.26 Minutes
Pausing scraper for 0 seconds.`

**Comment by Graphicscore** [comment]
As a temporary solution you can use the last release instead of the master branch. Nevertheless something is broken on source level

**Comment by phishyphun** [comment]
I used latest release and instead of finishing with only metadata scraped it just hangs at 0 download speed and never downloads:

`Scrape Processing
Name: lilboothang
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
1
Type: Profile
100%|█████████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:00<00:00, 6.92MB/s]
Type: Stories
Processing Scraped Stories
100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 2330.35it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 3496.50it/s]
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
100%|████████████████████████████████████████████████████████████████████████████| 1067/1067 [00:00<00:00, 2754.61it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|█████████████████████████████████████████████████████████████████████████████| 1067/1067 [00:01<00:00, 709.74it/s]
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 3397.17it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|█████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 799.28it/s]
Scrape Completed

Download Processing
Name: lilboothang | Type: Stories | Count: 7 | Directory: C:\Users\willm\Downloads\OnlyFans-7.6.1x\OnlyFans-7.6.1\.sites

0it [00:00, ?it/s]`

**Comment by blanuk** [comment]
same here. fansly works, but only seams to be broken. its scraping not the selected subscription and no content :/ not even with the latest release

**Comment by robotprom** [comment]
I am having a similar issue where it only scrapes avatars and headers, but will not scrape any other content, free or paid. the output in the terminal is weird too: 

`Scraping Subscriptions
Scrape Processing
Name: model I'm scraping
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Stories
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████| 105/105 [00:00<00:00, 1781.08it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████| 105/105 [00:00<00:00, 2101.22it/s]
Type: Archived
Type: Chats
Type: Messages
Processing Scraped Messages
100%|███████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 891.15it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 996.57it/s]
Type: Highlights
Type: MassMessages
Scrape Completed

Scraping Paid Content
Scraping - other model | 1 / 18
Scraping - other model | 2 / 18
Scraping - other model | 3 / 18
Scraping - other model | 4 / 18
Scraping - other model | 5 / 18
Scraping - other model | 6 / 18
Scraping - other model | 7 / 18
Scraping - other model | 8 / 18
Scraping - other model | 9 / 18
Scraping - other model | 10 / 18
Scraping - other model | 11 / 18
Scraping - other model | 12 / 18
Scraping - other model | 13 / 18
Scraping - model I'm scraping | 14 / 18
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████| 105/105 [00:00<00:00, 1780.44it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████| 105/105 [00:00<00:00, 2144.12it/s]
Processing Scraped Messages
100%|███████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 800.50it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1334.38it/s]
Scraping - other model | 15 / 18
Scraping - other model | 16 / 18
Scraping - other model | 17 / 18
Scraping - other model | 18 / 18
Scraping Message Content
Scrape Processing
Name: model I'm scraping
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
`

**Comment by blanuk** [comment]
well, maybee it helps, but i set selenium to 4.0.0 and now it works.

**Comment by alvin-hong** [comment]
Has a fix been posted or is paid content just not working?
