### ISSUE TITLE
Is this Project Dead?

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINALS/OnlyFans#506]
Is this the only scrapper available? Hasn't been updated in a while, anyone know of any working forks? Mine was working fine till I had to redo windows. But now it freezes on downloading.

**Comment by fxckinghostile** [comment]
I've had a few issues here and there but a clean install of the scraper has fix most . I found a fork called UltimaScraper awhile back but cant seem to find it again

**Comment by lordoffools** [comment]
I hope it's not dead! @DIGITALCRIMINALS and the overall community here has been the best.

@DIGITALCRIMINALS are you still with us? 👍

**Comment by DIGITALCRIMINALS** [comment]
I'm still alive, and working on something
![image](https://user-images.githubusercontent.com/89371864/178336927-9aec63ca-54e2-4a46-aed5-2f4c5701f355.png)

**Comment by lordoffools** [comment]
Great to hear from you, @DIGITALCRIMINALS! Glad you're still alive and doing well.

And thanks for everything you and the community have done over the years here.

**Comment by OFfriend** [comment]
I also check every day to see if there are any major issues here.

**Comment by zeldatp151** [comment]
> 

so then is the fansly issue already being worked on?

**Comment by DIGITALCRIMINALS** [comment]
> > 
> 
> so then is the fansly issue already being worked on?

I'm aware of it, but I haven't started working on it. I have to finish the new UI first.

**Comment by DIGITALCRIMINALS** [comment]
I need a TUI since I've outgrown the limits of a traditional CLI, but at this moment it's optional due to bugs but I am removing the old UI once I add multi-threaded jobs and queues to the script since there will be no way print those nicely, and I don't want the extra work. 

Having a TUI means the script can handle different jobs (Authentication, Scraping and Downloading) at the same time across multiple cpus/threads and report the information on the screen without creating multiple lines of text. 

The script can still be ran automatically in both formats.

**Comment by MonkeyKingViper** [comment]
The growth in the project sounds like it will be fantastic. Many props to you

**Comment by MillerTimeJones** [comment]
Any idea of a date when we can expect a new build? the latest one was all the way back last year and so many people are having issues now it's looking like for 90% of people unusable.

Myself one of them none of the claimed solutions people are posting work.

**Comment by LFS900** [comment]
I second that! I've been trying everything, an older version to see if it works. I also can't seem to find the 7.6.1 version anymore anyway. But nothing works. I can log in, select a certain subscription, then it gives an error. I really wanna catch up with what's been downloaded. Hope some kind of update can be shared soon, even if it's just an informational one.

**Comment by GooseWhoIsLoose** [comment]
> I'm still alive, and working on something ![image](https://user-images.githubusercontent.com/89371864/178336927-9aec63ca-54e2-4a46-aed5-2f4c5701f355.png)

That looks awesome! Can't wait to try it out when it drops! :)

**Comment by maxcom99** [comment]
@DIGITALCRIMINALS pardon the tag but this is getting a bit painful with the state of manual fixes for folks... whats the good word sir?

**Comment by DIGITALCRIMINALS** [comment]
> Any update on the new project?

![image](https://user-images.githubusercontent.com/89371864/205181515-90772c9c-0c9c-45dd-b743-3f67def75f47.png)
![image](https://user-images.githubusercontent.com/89371864/205183633-7a6343d3-1376-4474-848b-d3608e97d11b.png)

The TUI is about 90% away from being usable, and the design isn't finished.
I just need to add progress bars so we can see what's being downloaded instead of the ambiguous "download".

I had to split the script into two halves. Server and TUI.
The server can still run without the TUI.
The server and TUI will communicate with each other using websockets.
Theoretically the relationship will be a one server to many TUIs, and vice vera... but it's best to interact with the server from one main TUI.

There's still some bugs with Textual and some server optimisations needed but it still works great.

**Comment by DIGITALCRIMINALS** [comment]
Works nicely, I'll release soon.
![image](https://user-images.githubusercontent.com/89371864/205189989-71892beb-f22a-4971-8f4a-b4a0ce1bf7bf.png)

**Comment by sanctifyy** [comment]
yooo good work dude

**Comment by MillerTimeJones** [comment]
> Works nicely, I'll release soon. ![image](https://user-images.githubusercontent.com/89371864/205189989-71892beb-f22a-4971-8f4a-b4a0ce1bf7bf.png)

Looking forward to this.

Thank you for your effort over the years.

**Comment by RickyBubbles** [comment]
Are you able to grab purchased content from DMs? (Or free content from DMs for that matter, since some models sell in exchange for tips instead of pay to unlock).

this seems to be a challenge for other tools, but yours used to do it…

**Comment by kccomikeyga** [comment]
Unfortunately we're waiting on that fix.  @DIGITALCRIMINALS will release when it's ready.

**Comment by DIGITALCRIMINALS** [comment]
Feel free to use the test branch, I've updated a lot of things, I don't know if everything is fixed though.

https://github.com/DIGITALCRIMINALS/OnlyFans/tree/Test

**Comment by MillerTimeJones** [comment]
> Feel free to use the test branch, I've updated a lot of things, I don't know if everything is fixed though.
> 
> https://github.com/DIGITALCRIMINALS/OnlyFans/tree/Test


How do we use that?
