### ISSUE TITLE
pypoetry install error on docker build

### ISSUE THREAD

**Issue by gelatinousdonk** [DIGITALCRIMINALS/OnlyFans#631]
When trying to build the image, the following line:
`RUN /usr/local/share/pypoetry/bin/poetry install --no-dev`
is resulting in the following error:
```
 => ERROR [6/7] RUN /usr/local/share/pypoetry/bin/poetry install --no-dev                                          0.4s
------
 > [6/7] RUN /usr/local/share/pypoetry/bin/poetry install --no-dev:
#10 0.403 /bin/sh: 1: /usr/local/share/pypoetry/bin/poetry: not found
------
executor failed running [/bin/sh -c /usr/local/share/pypoetry/bin/poetry install --no-dev]: exit code: 127
```

**Comment by ThePornHelper** [comment]
I have this exact same problem, it was working perfectly fine a few days ago.

**Comment by ThePornHelper** [comment]
I'm not sure exactly as to what is happening because I'm no expert in coding but after three days of research I seem to have fixed my issue. Here is what I did.

1.  I downloaded the latest version of Python which is python 3.10

2. I then cd into the OnlyFans folder

3. Then I ran `pip3 install poetry` after than I ran `poetry install --no-dev` both in terminal.

4. After that I ran `sudo /Applications/Python\ 3.10/Install\ Certificates.command` in terminal which I found thanks to this issue (https://github.com/DIGITALCRIMINALS/OnlyFans/issues/32#issuecomment-941257099)

5. To run the code I typed `python3.10 start_ofd.py` in the terminal, all the other ones did not work for me.

If you get a error that looks like this:
``` File /home/bob/Downloads/OnlyFans/apis/onlyfans/classes/user_model.py, line 283, in get_highlights
results = [create_highlight(x) for x in results[data]]
KeyError: 'data'
```
That error is solved here https://github.com/DIGITALCRIMINALS/OnlyFans/pull/605#issuecomment-1234734787

Also I ran into a problem where the content would not be downloaded, in case you get the same problem here is the issue that can possibly fix it. https://github.com/DIGITALCRIMINALS/OnlyFans/issues/465#issuecomment-1146249588

Hope this helps.
