### ISSUE TITLE
It only downloads the last images and videos from a multi-image/video posts.

### ISSUE THREAD

**Issue by zynx202** [DIGITALCRIMINALS/OnlyFans#688]
It will only download the first image or video from the multi-image/video post. Is there a fix to this already? (I surfed through the issues I didn't find any)

**Comment by zynx202** [comment]
Upon closer inspection It seems that it only downloads the last video or image in a multi image/video posts.

**Comment by Squidu** [comment]
I just figured this out. It looks like the scraper doesn't have a way to handle duplicate filenames, so instead it just overwrites them with the next photo. That's why you're only seeing the last one in a post that contains multiple. To fix this, you need to add a variable to the filename format that will lead to unique filenames. 

Using "{date}_{value}_UTC_OF.{ext}" will lead to your issue, I've fixed it by using media_id which is a unique string for each individual photo/video, "{date}_{media_id}_{value}_UTC_OF.{ext}" 

Unfortunately, the only way I was able to fully correct the issue, was to create a brand-new directory and fully scrape everything from scratch. It appears that the files don't get automatically renamed like they usually do when changing the filename format. 

Good luck, hope that helps.

**Comment by zynx202** [comment]
Thanks a lot, this fixed the issue like a charm.

**Comment by dantdanielson** [comment]
> 

Where in the code do I make this change?

**Comment by Squidu** [comment]
@dantdanielson
The above post refers to the _filename_format_ setting within the file _config.json_.

**Comment by DIGITALCRIMINALS** [comment]
I mean it literally says here that you need a unique identifier and that's on by default.

https://github.com/DIGITALCRIMINALS/OnlyFans/tree/master#filename_format
