### ISSUE TITLE
Not Working for Paid Subscriptions

### ISSUE THREAD

**Issue by MisterDiggy** [DIGITALCRIMINALS/OnlyFans#711]
It just says...

Missing 300 Posts... Retrying...
Scrape Attempt: 2/100
Missing 300 Posts... Retrying...
Scrape Attempt: 3/100
Missing 600 Posts... Retrying...
Scrape Attempt: 4/100
Missing 800 Posts... Retrying...
Scrape Attempt: 5/100
Missing 750 Posts... Retrying...
Scrape Attempt: 6/100
Missing 620 Posts... Retrying...
Scrape Attempt: 7/100

Over and over... Anyone have a fix?

**Comment by rknightion** [comment]
You don't have a subscription anymore for that user is usually what prompts those in my experience.
Sometimes as well a creator will delete/disable their account while you're subscribed which can lead to these messages forevermore (even if your subscription would have long since expired) as internally at OF you're still subscribed to an account you can no longer access.

Wait until all the scrape attempts have passed and the script will continue processing as normal :)
